# This will be our configuration file for the system. 
# We can add various settings here for our system.


# These are some settings that I can think of for the plant monitoring use
ph:

temperature:

humidity:

camera:

database:

sensors